Adding shinyjster tests for updateDateRangePicker functionality
rstudio/shinycoreci-apps pull request #125
Opened 2021-03-17 19:09 UTC by MadhulikaTanuboddi

Connected to https://github.com/rstudio/shinycoreci-apps/issues/124

shinyjster test covers the following cases

1. For every slider value change (currently from 6 - 25), we are verifying
   a. From date is (slider value - 1).
   b  To date is (slider value + 1)
   c. Possible selectable dates in both from and to date pickers are (slider value - 5) and (slider value + 5). For ex: for a slider value "7", this would be [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

2. Currently using hard coded month/year in the date picker. In the future, will work on using dynamic dates

2021-03-17 20:25 UTC, wch commented on apps/212-daterangepicker/app.R
> +    bindEvent(input$n)
I don't think this `bindEvent` is necessary, since the observer's only reactive input is `input$n`.

2021-03-17 20:25 UTC, wch commented on apps/212-daterangepicker/app.R
> +library(magrittr)
Not necessary since the `bindEvent()` below can be removed.

2021-03-17 20:35 UTC, wch commented
Looks good overall! I suggest we test fewer dates, though -- testing every single value from `slider_min` to `slider_max` doesn't really add anything compared to testing, say, 3 or 4 dates, but it does cause the tests to take more time.

2021-03-18 14:21 UTC, schloerke requested changes
The windows failure is independent of the code change.

LGTM given Winston's comments

2021-03-18 17:26 UTC, schloerke approved these changes

2021-03-18 20:09 UTC, merged